volumes:
  mysql-data:
  valkey-data:

networks:
  helium:
    driver: bridge

services:
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: helium
      MYSQL_USER: heliumuser
      MYSQL_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - helium
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: valkey/valkey:alpine
    volumes:
      - valkey-data:/data
    ports:
      - "6379:6379"
    networks:
      - helium
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    image: helium-backend
    env_file: .env.production
    volumes:
      - ./docker-storage:/var/www/html/storage
      - ./docker-storage/app:/var/www/html/storage/app
      - ./docker-storage/framework/views:/var/www/html/storage/framework/views
      - ./docker-storage/framework/testing:/var/www/html/storage/framework/testing
    ports:
      - "8000:80"
    networks:
      - helium
    depends_on:
      - redis
      - mysql

  queue:
    image: helium-backend
    env_file: .env.production
    entrypoint: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    volumes:
      - ./docker-storage/app:/var/www/html/storage/app
    networks:
      - helium
    depends_on:
      - backend

  frontend:
    image: helium-frontend
    ports:
      - "3000:3000"
    networks:
      - helium
 